name: Angular GitHub CI
on:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
          npm ci
      - name: Build
        run: |
          npm run build
      - name: Deploy
        run: |
          npm run deploy